# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d85f204bafd0687a7c8a583f69bd9903ca6386eb77b82b15aac9e41c45d869c97a3e52f80c338d3bf4f22e1d304cfae339bef9a44c50099a948588996b70412

test:
  secret_key_base: a5194e66c97d0137ea91340144bfae0083c8adaa22d8efa11f2ac97d9a14a897fda70f192c815abc6117760ac5c2cc704da4c04b38ddbeffb943a104e222d582

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
